name: Testing
on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15
      - name: setup
        run: npm ci
      - name: setup jest
        run: npm i -g jest
      - name: test
        run: npm test
